[package]
name = "my_project"
version = "0.1.0"
edition = "2024"

[dependencies]

# Zależności tylko do testów / benchmarków
[dev-dependencies]
criterion = "0.5"

# Pliki z benchmarkami: benches/my_bench.rs
[[bench]]
name = "my_bench"
harness = false
